lobby:
  message-for-next-page: "按 TAB 切换下一页... %currentpage%/%pagecount%"
  make-public-message: "禁止设置为公开"
role:
  unknown:
    name: "未知"
    description: "当你未被分配职业或者其他特殊情况，你会是这个职业"
  global:
    max-num: "<color=#808080>最大职业数量</color>"
    allow-start-meeting: "<color=#CEC7C7>允许启动会议</color>"
    allow-report-body: "<color=#CEC7C7>允许报告尸体</color>"
  impostor:
    impostor:
      name: "伪装者"
      description: "击杀船员，造成破坏"
  crewmate:
    crewmate:
      name: "船员"
      description: "找出伪装者，投出内鬼"
    bait:
      name: "诱饵"
      description: "你被击杀时，凶手会自动报告"
    sheriff:
      name: "警长"
      description: "你可以击杀所有非船员玩家，但是错杀船员的后果是致命的"
  neutral:
    jester:
      name: "小丑"
      description: "你会在被驱逐后获胜"
camp:
  unknown:
    name: "未知阵营"
    description: "未知的阵营"
  impostor:
    name: "伪装者阵营"
    description: "杀死船员"
  neutral:
    name: "中立阵营"
    description: "掌握好权重"
  crewmate:
    name: "船员阵营"
    description: "完成任务，找出内鬼"
menu:
  general:
    name: "COG设置"
    save-game-configs: "保存游戏设置"
  impostor:
    name: "内鬼职业设置"
  neutral:
    name: "中立职业设置"
  crewmate:
    name: "船员职业设置"
  addons:
    name: "副职业设置"
option:
  main:
    cog-options: "COG选项"
    reload-configs: "替换且重新加载语言文件且重启游戏"
    github: "Github"
    qq: "QQ"
    discord: "Discord"
    beta-version-registered-user-display: "测试用户数量: %registered-num%"
  enable: "<color=#5DB927>开启</color>"
  disable: "<color=#F20D0D>关闭</color>"
sidebar-text:
  original: "<color=#9AFF00>原版设置</color>"
  neutral: "<color=#9AFF00>中立设置</color>"
  mod: "<color=#9AFF00>模组设置</color>"
  addons: "<color=#9AFF00>副职业设置</color>"
  impostor: "<color=#9AFF00>伪装者设置</color>"
  crewmate: "<color=#9AFF00>船员设置</color>"