lobby:
  make-public-message: "禁止设置为公开"
role:
  unknown:
    name: "未知"
    description: "当你未被分配职业或者其他特殊情况，你会是这个职业"
  global:
    max-num: "最大职业数量"
    allow-start-meeting: "允许启动会议"
    allow-report-body: "允许报告尸体"
    kill-cooldown: "击杀冷却时间"
  impostor:
    impostor:
      name: "伪装者"
      description: "击杀船员，造成破坏"
    cleaner:
      name: "清洁工"
      description: "协助队友，清理尸体"
      desc-long: "清洁工可以清理船员的尸体。清洁工可以击杀，但是击杀和清理共用冷却"
      clean-cd: "清理尸体冷却"
    eraser:
      name: "抹除者"
      description: "抹除别人的职业"
      desc-long: "抹除者可以立即抹除他人的职业，但值得注意的是每次抹除之后抹除冷却会变得更长"
      menu:
        initial-erase-cd: "初始擦除冷却"
        increase-cd-after-erasing: "擦除后增加冷却"
        can-erase-imps: "可擦除内鬼职业"
  crewmate:
    crewmate:
      name: "船员"
      description: "找出伪装者，投出内鬼"
    bait:
      name: "诱饵"
      description: "你被击杀时，凶手会自动报告"
      killer-report-delay: "凶手自报延迟"
      warn-killer: "闪光警告凶手"
    sheriff:
      name: "警长"
      description: "你可以击杀所有非船员玩家，但是错杀船员的后果是致命的"
      kill-cd: "击杀冷却"
    spy:
      name: "间谍"
      description: "我是内鬼！"
      desc-long: "在所有内鬼眼中你的名字是红色的，但是你实际是船员"
    vigilante:
      name: "侠客"
      description: "行侠仗义！"
      desc-long: "你拥有一次击杀机会，当船员数量小于等于3时你会额外获得一次击杀机会"
  neutral:
    jester:
      name: "小丑"
      description: "你会在被驱逐后获胜"
    vulture:
      name: "秃鹫"
      description: "船员们的血肉，味道又如何呢？"
      desc-long: "你可以吞噬船员的尸体，当吞噬尸体数量达到一定值后会直接胜利"
      eat-cd: "吞噬冷却"
      count-to-win: "胜利吞噬尸体数"
      has-arrow: "箭头指向尸体"
  sub-roles:
    guesser:
      name: "赌怪"
      description: "生命就是豪赌"
      desc-long: "你可以在会议上猜测他人的职业，但如果猜测失败你将会自杀"
      max-guess-time: "最大猜测次数"
      guess-continuously: "连续赌注"
    lighter:
      name: "灯人"
      description: "要相信光！"
      desc-long: "你的视野大小不受影响"
    lover:
      name: "恋人"
      description: "你与 %lover% 坠入了爱河"
      count-option: "恋人对数"
      die-together: "恋人共死"
      private-chat: "启用私聊频道"
camp:
  unknown:
    name: "未知阵营"
    description: "未知的阵营"
  impostor:
    name: "伪装者阵营"
    description: "杀死船员"
  neutral:
    name: "中立阵营"
    description: "掌握好权重"
  crewmate:
    name: "船员阵营"
    description: "完成任务，找出内鬼"
  addon: "附加职业"
game-setting:
  view-description:
    general: "预览游戏大厅的常规设置。"
    role: "预览游戏大厅的职业设置。"
  general:
    title: "COG设置"
    load-preset: "加载预设"
    save-preset: "保存预设"
    debug-mode: "<color=#9AFF00>调试模式</color>"
    max-sub-role-number: "最大副职业数量"
option:
  main:
    cog-options: "COG选项"
    load-custom-lang: "加载自定义语言文件"
    unload-mod:
      name: "临时禁用模组"
      success: "模组已成功被临时禁用！\n如果您仍想要继续游玩模组，请重启游戏"
      error-in-game: "请先离开本局游戏再进行操作"
    github: "Github"
    qq: "QQ"
    discord: "Discord"
    update-button-string: "检查更新"
    update:
      up-to-date: "你已经更新到最新版本"
      non-check: "未能找到最新版本"
      fetched: "搜索到最新版：%version%\r\n%description%\r\n是否安装？"
  enable: "<color=#5DB927>开启</color>"
  disable: "<color=#F20D0D>关闭</color>"
action:
  kill: "击杀"
  clean: "清理"
  erase-action: "抹除"
  annihilate: "湮灭"
  eat-action: "吞噬"
game:
  end:
    show-players-roles-message: "玩家职业: "
    wins:
      impostor: "伪装者胜利"
      crewmate: "船员胜利"
      neutral: "%player% 胜利"
  survival-data:
    alive: "存活"
    disconnected: "掉线"
    default: "死亡"
    unknown: "未知"
  exile:
    default: "%player% 是 %role%。"
    alive-player-info: "剩余 %crew% 个船员， %neutral% 个中立， %imp% 个内鬼。"
    lover-message: "%player% 是 %role%。\n%lover% 似乎由于伤心过度殉情了。"
  chat:
    system-message: "<b>【系统消息】</b>\0"