lobby:
  message-for-next-page: "按 TAB 切换下一页... %currentpage%/%pagecount%"
  make-public-message: "禁止设置为公开"

role:
  global:
    max-num: "<color=#808080>最大职业数量</color>"
    allow-start-meeting: "<color=#CEC7C7>允许启动会议</color>"
    allow-report-body: "<color=#CEC7C7>允许报告尸体</color>"
  impostor:
    impostor:
      name: "伪装者"
      description: "击杀船员，造成破坏"
  crewmate:
    crewmate:
      name: "船员"
      description: "找出伪装者，投出内鬼"
  neutral:
    jester:
      name: "小丑"
      description: "你会在被驱逐后获胜"

menu:
  general:
    name: "COG设置"
    save-game-configs: "保存游戏设置"
  impostor:
    name: "内鬼职业设置"
  neutral:
    name: "中立职业设置"
  crewmate:
    name: "船员职业设置"
  addons:
    name: "副职业设置"
option:
  main:
    cog-options: "COG选项"
    reload-configs: "替换且重新加载语言文件且重启游戏"
    github: "Github"
    qq: "QQ"
    discord: "Discord"
  enable: "<color=#5DB927>开启</color>"
  disable: "<color=#F20D0D>关闭</color>"
  
sidebar-text:
  original: "<color=#FF0000>原版设置</color>"
  neutral: "<color=#FF0000>中立设置</color>"
  mod: "<color=#FF0000>模组设置</color>"
  addons: "<color=#FF0000>副职业设置</color>"
  impostor: "<color=#FF0000>伪装者设置</color>"
  crewmate: "<color=#FF0000>船员设置</color>"