name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  
    - name: Build
      run: dotnet build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: COG Artifact
        path: COG/bin

    - name: Upload Objects
      uses: actions/upload-artifact@v3
      with:
        name: Objects
        path: COG/obj
